version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (none needed for static site)"
  build:
    commands:
      - echo "Starting build phase"
      - echo "No build tools required for static HTML/CSS/JS"
      - echo "Build phase complete"

artifacts:
  files:
    - "**/*"
  discard-paths: no
